development:
  adapter: postgresql
  encoding: unicode
  database: indie88_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: indie88_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: indie88_production
  pool: 5
