Artist.where(name:"Artist").update_all(fem_level: 4)
Artist.where(name:"Florence + The Machine").update_all(fem_level: 2)
Artist.where(name:"Fitz & The Tantrums").update_all(fem_level: 1)
Artist.where(name:"The Cure").update_all(fem_level: 0)
Artist.where(name:"The Weakerthans").update_all(fem_level: 0)
Artist.where(name:"Cayucas").update_all(fem_level: 0)
Artist.where(name:"Sam Roberts").update_all(fem_level: 0)
Artist.where(name:"Foster The People").update_all(fem_level: 0)
Artist.where(name:"The Sheepdogs").update_all(fem_level: 0)
Artist.where(name:"Johnny Cash").update_all(fem_level: 0)
Artist.where(name:"Royal Canoe").update_all(fem_level: 0)
Artist.where(name:"Death Cab for Cutie").update_all(fem_level: 0)
Artist.where(name:"Moby").update_all(fem_level: 0)
Artist.where(name:"The Mowgli's").update_all(fem_level: 1)
Artist.where(name:"The Lumineers").update_all(fem_level: 1)
Artist.where(name:"Tokyo Police Club").update_all(fem_level: 0)
Artist.where(name:"Foo Fighters").update_all(fem_level: 0)
Artist.where(name:"Arcade Fire").update_all(fem_level: 1)
Artist.where(name:"Vance Joy").update_all(fem_level: 0)
Artist.where(name:"Tame Impala").update_all(fem_level: 0)
Artist.where(name:"Modest Mouse").update_all(fem_level: 0)
Artist.where(name:"Cage The Elephant").update_all(fem_level: 0)
Artist.where(name:"The Strumbellas").update_all(fem_level: 1)
Artist.where(name:"Talking Heads").update_all(fem_level: 1)
Artist.where(name:"Dear Rouge").update_all(fem_level: 2)
Artist.where(name:"Cake").update_all(fem_level: 0)
Artist.where(name:"The New Pornographers").update_all(fem_level: 1)
Artist.where(name:"Radiohead").update_all(fem_level: 0)
Artist.where(name:"Walk Off the Earth").update_all(fem_level: 1)
Artist.where(name:"Beck").update_all(fem_level: 0)
Artist.where(name:"Vampire Weekend").update_all(fem_level: 0)
Artist.where(name:"The Strokes").update_all(fem_level: 0)
Artist.where(name:"Mumford & Sons").update_all(fem_level: 0)
Artist.where(name:"Jack White").update_all(fem_level: 0)
Artist.where(name:"Alvvays").update_all(fem_level: 2)
Artist.where(name:"Bedouin Soundclash").update_all(fem_level: 0)
Artist.where(name:"Silversun Pickups").update_all(fem_level: 1)
Artist.where(name:"Sloan").update_all(fem_level: 0)
Artist.where(name:"USS (Ubiquitous Synergy Seeker)").update_all(fem_level: 0)
Artist.where(name:"The Verve").update_all(fem_level: 0)
Artist.where(name:"The Darcys").update_all(fem_level: 0)
Artist.where(name:"Pixies").update_all(fem_level: 1)
Artist.where(name:"Franz Ferdinand").update_all(fem_level: 0)
Artist.where(name:"The Pack A.D.").update_all(fem_level: 2)
Artist.where(name:"The National").update_all(fem_level: 0)
Artist.where(name:"Metric").update_all(fem_level: 2)
Artist.where(name:"Arctic Monkeys").update_all(fem_level: 0)
Artist.where(name:"Death from Above 1979").update_all(fem_level: 0)
Artist.where(name:"Daft Punk").update_all(fem_level: 0)
Artist.where(name:"Said the Whale").update_all(fem_level: 1)
Artist.where(name:"Imaginary Cities").update_all(fem_level: 2)
Artist.where(name:"Broken Bells").update_all(fem_level: 0)
Artist.where(name:"Foster the People").update_all(fem_level: 0)
Artist.where(name:"Mother Mother").update_all(fem_level: 1)
Artist.where(name:"The Zolas").update_all(fem_level: 0)
Artist.where(name:"Oasis").update_all(fem_level: 0)
Artist.where(name:"Phoenix").update_all(fem_level: 0)
Artist.where(name:"the Tragically Hip").update_all(fem_level: 0)
Artist.where(name:"Capital Cities").update_all(fem_level: 0)
Artist.where(name:"Rah Rah").update_all(fem_level: 3)
Artist.where(name:"R.E.M.").update_all(fem_level: 0)
Artist.where(name:"Hannah Georgas").update_all(fem_level: 2)
Artist.where(name:"Atlas Genius").update_all(fem_level: 0)
Artist.where(name:"Broken Social Scene").update_all(fem_level: 1)
Artist.where(name:"Amy Winehouse").update_all(fem_level: 2)
Artist.where(name:"The White Stripes").update_all(fem_level: 1)
Artist.where(name:"M83").update_all(fem_level: 0)
Artist.where(name:"Matt Mays & El Torpedo").update_all(fem_level: 0)
Artist.where(name:"Imagine Dragons").update_all(fem_level: 0)
Artist.where(name:"Alt-J").update_all(fem_level: 0)
Artist.where(name:"Bastille").update_all(fem_level: 0)
Artist.where(name:"The Velvet Underground").update_all(fem_level: 0)
Artist.where(name:"Serena Ryder").update_all(fem_level: 2)
Artist.where(name:"Of Monsters and Men").update_all(fem_level: 2)
Artist.where(name:"Hollerado").update_all(fem_level: 0)
Artist.where(name:"MGMT").update_all(fem_level: 0)
Artist.where(name:"Phantogram").update_all(fem_level: 3)
Artist.where(name:"Born Ruffians").update_all(fem_level: 0)
Artist.where(name:"Weezer").update_all(fem_level: 0)
Artist.where(name:"Matthew Good").update_all(fem_level: 0)
Artist.where(name:"Half Moon Run").update_all(fem_level: 0)
Artist.where(name:"Lorde").update_all(fem_level: 2)
Artist.where(name:"The Marble Index").update_all(fem_level: 0)
Artist.where(name:"Lord Huron").update_all(fem_level: 0)
Artist.where(name:"Fast Romantics").update_all(fem_level: 1)
Artist.where(name:"The Black Keys").update_all(fem_level: 0)
Artist.where(name:"Jane's Addiction").update_all(fem_level: 0)
Artist.where(name:"Fiona Apple").update_all(fem_level: 2)
Artist.where(name:"David Bowie").update_all(fem_level: 0)
Artist.where(name:"Kevin Drew").update_all(fem_level: 0)
Artist.where(name:"k-os").update_all(fem_level: 0)
Artist.where(name:"The Smiths").update_all(fem_level: 0)
Artist.where(name:"Wintersleep").update_all(fem_level: 0)
Artist.where(name:"Queens of the Stone Age").update_all(fem_level: 0)
Artist.where(name:"The Raconteurs").update_all(fem_level: 0)
Artist.where(name:"MS MR").update_all(fem_level: 2)
Artist.where(name:"Library Voices").update_all(fem_level: 1)
Artist.where(name:"The Clash").update_all(fem_level: 0)
Artist.where(name:"Interpol").update_all(fem_level: 0)
Artist.where(name:"Nirvana").update_all(fem_level: 0)
Artist.where(name:"City and Colour").update_all(fem_level: 0)
Artist.where(name:"Johnny Cash & Willie Nelson").update_all(fem_level: 0)
Artist.where(name:"The Tragically Hip").update_all(fem_level: 0)
Artist.where(name:"Yeah Yeah Yeahs").update_all(fem_level: 2)
Artist.where(name:"July Talk").update_all(fem_level: 2)
Artist.where(name:"The Shins").update_all(fem_level: 0)
Artist.where(name:"Tegan and Sara").update_all(fem_level: 2)
Artist.where(name:"The Arkells").update_all(fem_level: 0)
Artist.where(name:"The Stills").update_all(fem_level: 0)
Artist.where(name:"Sandbox").update_all(fem_level: 0)
Artist.where(name:"Gorillaz").update_all(fem_level: 0)
Artist.where(name:"The Chemical Brothers").update_all(fem_level: 0)
Artist.where(name:"M.I.A.").update_all(fem_level: 2)
Artist.where(name:"Young the Giant").update_all(fem_level: 0)
Artist.where(name:"Bob Marley & The Wailers").update_all(fem_level: 0)
Artist.where(name:"The Neighbourhood").update_all(fem_level: 0)
Artist.where(name:"Semisonic").update_all(fem_level: 0)
Artist.where(name:"Mounties").update_all(fem_level: 0)
Artist.where(name:"The Fratellis").update_all(fem_level: 0)
Artist.where(name:"The Naked and Famous").update_all(fem_level: 2)
Artist.where(name:"Wake Owl").update_all(fem_level: 0)
Artist.where(name:"OutKast").update_all(fem_level: 0)
Artist.where(name:"Constantines").update_all(fem_level: 0)
Artist.where(name:"Depeche Mode").update_all(fem_level: 0)
Artist.where(name:"The Killers").update_all(fem_level: 0)
Artist.where(name:"Dum Dum Girls").update_all(fem_level: 4)
Artist.where(name:"Edward Sharpe & The Magnetic Zeros").update_all(fem_level: 1)
Artist.where(name:"Bob Dylan").update_all(fem_level: 0)
Artist.where(name:"Crystal Castles").update_all(fem_level: 2)
Artist.where(name:"The Avett Brothers").update_all(fem_level: 0)
Artist.where(name:"Champion").update_all(fem_level: 0)
Artist.where(name:"Young Empires").update_all(fem_level: 0)
Artist.where(name:"Against Me!").update_all(fem_level: 2)
Artist.where(name:"Ellie Goulding").update_all(fem_level: 2)
Artist.where(name:"Arthur Alexander").update_all(fem_level: 0)
Artist.where(name:"The Temper Trap").update_all(fem_level: 0)
Artist.where(name:"Sam Roberts Band").update_all(fem_level: 0)
Artist.where(name:"Pearl Jam").update_all(fem_level: 0)
Artist.where(name:"Sex Pistols").update_all(fem_level: 0)
Artist.where(name:"K-Os").update_all(fem_level: 0)
Artist.where(name:"Hot Hot Heat").update_all(fem_level: 0)
Artist.where(name:"Stars").update_all(fem_level: 3)
Artist.where(name:"Supergrass").update_all(fem_level: 0)
Artist.where(name:"Neutral Milk Hotel").update_all(fem_level: 0)
Artist.where(name:"Feist").update_all(fem_level: 2)
Artist.where(name:"Gary Clark Jr.").update_all(fem_level: 0)
Artist.where(name:"U2").update_all(fem_level: 0)
Artist.where(name:"Arkells").update_all(fem_level: 0)
Artist.where(name:"Cage the Elephant").update_all(fem_level: 0)
Artist.where(name:"Dan Mangan").update_all(fem_level: 0)
Artist.where(name:"Modern English").update_all(fem_level: 0)
Artist.where(name:"Red Hot Chili Peppers").update_all(fem_level: 0)
Artist.where(name:"Kings of Leon").update_all(fem_level: 0)
Artist.where(name:"New Radicals").update_all(fem_level: 0)
Artist.where(name:"OK Go").update_all(fem_level: 0)
Artist.where(name:"Matthew Good Band").update_all(fem_level: 0)
Artist.where(name:"The Jam").update_all(fem_level: 0)
Artist.where(name:"Coldplay").update_all(fem_level: 0)
Artist.where(name:"Jet").update_all(fem_level: 0)
Artist.where(name:"The Airborne Toxic Event").update_all(fem_level: 1)
Artist.where(name:"a-ha").update_all(fem_level: 0)
Artist.where(name:"Live").update_all(fem_level: 0)
Artist.where(name:"Passenger").update_all(fem_level: 0)
Artist.where(name:"Nine Inch Nails").update_all(fem_level: 0)
Artist.where(name:"Fun Lovin' Criminals").update_all(fem_level: 0)
Artist.where(name:"LCD Soundsystem").update_all(fem_level: 0)
Artist.where(name:"Elvis Costello").update_all(fem_level: 0)
Artist.where(name:"Uss").update_all(fem_level: 0)
Artist.where(name:"The Cranberries").update_all(fem_level: 2)
Artist.where(name:"Pilot Speed").update_all(fem_level: 0)
Artist.where(name:"Hawksley Workman").update_all(fem_level: 0)
Artist.where(name:"Hey Rosetta!").update_all(fem_level: 1)
Artist.where(name:"Joel Plaskett").update_all(fem_level: 0)
Artist.where(name:"Eddie Vedder").update_all(fem_level: 0)
Artist.where(name:"Outkast").update_all(fem_level: 0)
Artist.where(name:"Urge Overkill").update_all(fem_level: 0)
Artist.where(name:"Zerbin").update_all(fem_level: 0)
Artist.where(name:"Grouplove").update_all(fem_level: 1)
Artist.where(name:"Rancid").update_all(fem_level: 0)
Artist.where(name:"Madness").update_all(fem_level: 0)
Artist.where(name:"The Breeders").update_all(fem_level: 2)
Artist.where(name:"The Dandy Warhols").update_all(fem_level: 1)
Artist.where(name:"Phillip Phillips").update_all(fem_level: 0)
Artist.where(name:"Violent Femmes").update_all(fem_level: 0)
Artist.where(name:"Jamiroquai").update_all(fem_level: 0)
Artist.where(name:"The Lemonheads").update_all(fem_level: 0)
Artist.where(name:"blur").update_all(fem_level: 0)
Artist.where(name:"Devo").update_all(fem_level: 0)
Artist.where(name:"Spoon").update_all(fem_level: 0)
Artist.where(name:"Chromeo Feat Toro Y Moi").update_all(fem_level: 0)
Artist.where(name:"The Postal Service").update_all(fem_level: 1)
Artist.where(name:"Peter Bjorn and John").update_all(fem_level: 0)
Artist.where(name:"Lou Reed").update_all(fem_level: 0)
Artist.where(name:"Alabama Shakes").update_all(fem_level: 2)
Artist.where(name:"Neon Trees").update_all(fem_level: 1)
Artist.where(name:"Jets Overhead").update_all(fem_level: 1)
Artist.where(name:"Jeremy Fisher").update_all(fem_level: 0)
Artist.where(name:"Nick Cave & The Bad Seeds").update_all(fem_level: 0)
Artist.where(name:"The English Beat").update_all(fem_level: 0)
Artist.where(name:"Bran Van 3000").update_all(fem_level: 1)
Artist.where(name:"Plain White T's").update_all(fem_level: 0)
Artist.where(name:"The Bravery").update_all(fem_level: 0)
Artist.where(name:"The Xx").update_all(fem_level: 3)
Artist.where(name:"James").update_all(fem_level: 0)
Artist.where(name:"Talk Talk").update_all(fem_level: 0)
Artist.where(name:"The Cardigans").update_all(fem_level: 2)
Artist.where(name:"Ramones").update_all(fem_level: 0)
Artist.where(name:"Snow Patrol").update_all(fem_level: 0)
Artist.where(name:"Fatboy Slim").update_all(fem_level: 0)
Artist.where(name:"The Dudes").update_all(fem_level: 0)
Artist.where(name:"New Order").update_all(fem_level: 0)
Artist.where(name:"Iggy Pop").update_all(fem_level: 0)
Artist.where(name:"Blur").update_all(fem_level: 0)
Artist.where(name:"Sneaker Pimps").update_all(fem_level: 0)
Artist.where(name:"The Specials").update_all(fem_level: 0)
Artist.where(name:"Gotye").update_all(fem_level: 0)
Artist.where(name:"Edwyn Collins").update_all(fem_level: 0)
Artist.where(name:"Jeff Buckley").update_all(fem_level: 0)
Artist.where(name:"The Rural Alberta Advantage").update_all(fem_level: 2)
Artist.where(name:"Acres Of Lions").update_all(fem_level: 0)
Artist.where(name:"Wildlife").update_all(fem_level: 0)
Artist.where(name:"Django Django").update_all(fem_level: 0)
Artist.where(name:"The Jesus and Mary Chain").update_all(fem_level: 0)
Artist.where(name:"Braids").update_all(fem_level: 2)
Artist.where(name:"Band of Horses").update_all(fem_level: 0)
Artist.where(name:"Blink-182").update_all(fem_level: 0)
Artist.where(name:"Matt Mays").update_all(fem_level: 0)
Artist.where(name:"The Watchmen").update_all(fem_level: 0)
Artist.where(name:"Muse").update_all(fem_level: 0)
Artist.where(name:"John K. Samson").update_all(fem_level: 0)
Artist.where(name:"Blind Melon").update_all(fem_level: 0)
Artist.where(name:"Pulp").update_all(fem_level: 0)
Artist.where(name:"Hands & Teeth").update_all(fem_level: 1)
Artist.where(name:"The Dears").update_all(fem_level: 1)
Artist.where(name:"Sufjan Stevens").update_all(fem_level: 0)
Artist.where(name:"Japandroids").update_all(fem_level: 0)
Artist.where(name:"Teenage Kicks").update_all(fem_level: 0)
Artist.where(name:"Bombay Bicycle Club").update_all(fem_level: 0)
Artist.where(name:"Bahamas").update_all(fem_level: 0)
Artist.where(name:"Everclear").update_all(fem_level: 0)
Artist.where(name:"Yukon Blonde").update_all(fem_level: 0)
Artist.where(name:"Glasvegas").update_all(fem_level: 1)
Artist.where(name:"Rise Against").update_all(fem_level: 0)
Artist.where(name:"Jack Johnson").update_all(fem_level: 0)
Artist.where(name:"Jay Malinowski & The Deadcoast").update_all(fem_level: 0)
Artist.where(name:"Gnarls Barkley").update_all(fem_level: 0)
Artist.where(name:"We Are the City").update_all(fem_level: 0)
Artist.where(name:"Gord Downie & The Country Of Miracles").update_all(fem_level: 0)
Artist.where(name:"CHVRCHES").update_all(fem_level: 2)
Artist.where(name:"Austra").update_all(fem_level: 2)
Artist.where(name:"Cowboy Junkies").update_all(fem_level: 2)
Artist.where(name:"Sublime").update_all(fem_level: 0)
Artist.where(name:"Dinosaur Jr.").update_all(fem_level: 0)
Artist.where(name:"Kasabian").update_all(fem_level: 0)
Artist.where(name:"Real Estate").update_all(fem_level: 0)
Artist.where(name:"Bright Eyes").update_all(fem_level: 0)
Artist.where(name:"Warpaint").update_all(fem_level: 2)
Artist.where(name:"Tom Waits").update_all(fem_level: 0)
Artist.where(name:"Rheostatics").update_all(fem_level: 0)
Artist.where(name:"The Strypes").update_all(fem_level: 0)
Artist.where(name:"James Brown").update_all(fem_level: 0)
Artist.where(name:"White Lies").update_all(fem_level: 0)
Artist.where(name:"Two Hours Traffic").update_all(fem_level: 0)
Artist.where(name:"Uss (Ubiquitous Synergy Seeker)").update_all(fem_level: 0)
Artist.where(name:"No Doubt").update_all(fem_level: 2)
Artist.where(name:"A Ha").update_all(fem_level: 0)
Artist.where(name:"Smashing Pumpkins").update_all(fem_level: 1)
Artist.where(name:"Mazzy Star").update_all(fem_level: 2)
Artist.where(name:"Kongos").update_all(fem_level: 0)
Artist.where(name:"Hey Ocean!").update_all(fem_level: 2)
Artist.where(name:"Jimmy Eat World").update_all(fem_level: 0)
Artist.where(name:"Kate Bush").update_all(fem_level: 2)
Artist.where(name:"Allie X").update_all(fem_level: 2)
Artist.where(name:"The Russian Futurists").update_all(fem_level: 0)
Artist.where(name:"Local Natives").update_all(fem_level: 0)
Artist.where(name:"Weaves").update_all(fem_level: 2)
Artist.where(name:"Marnie Stern").update_all(fem_level: 2)
Artist.where(name:"Odonis Odonis").update_all(fem_level: 0)
Artist.where(name:"The Wet Secrets").update_all(fem_level: 1)
Artist.where(name:"Diana").update_all(fem_level: 2)
Artist.where(name:"The Unicorns").update_all(fem_level: 0)
Artist.where(name:"Alex Clare").update_all(fem_level: 0)
Artist.where(name:"Pup").update_all(fem_level: 0)
Artist.where(name:"Sebastien Grainger").update_all(fem_level: 0)
Artist.where(name:"Mac Demarco").update_all(fem_level: 0)
Artist.where(name:"Old 97's").update_all(fem_level: 0)
Artist.where(name:"Timber Timbre").update_all(fem_level: 0)
Artist.where(name:"Robert Ellis").update_all(fem_level: 0)
Artist.where(name:"Uncle Tupelo").update_all(fem_level: 0)
Artist.where(name:"Matt Costa").update_all(fem_level: 0)
Artist.where(name:"The Pogues").update_all(fem_level: 1)
Artist.where(name:"And You Will Know Us By The Trail").update_all(fem_level: 0)
Artist.where(name:"Joel Plaskett Emergency").update_all(fem_level: 0)
Artist.where(name:"Drive-By Truckers").update_all(fem_level: 0)
Artist.where(name:"Lake Street Dive").update_all(fem_level: 2)
Artist.where(name:"Nick Waterhouse").update_all(fem_level: 0)
Artist.where(name:"Stephen Malkmus & The Jicks").update_all(fem_level: 1)
Artist.where(name:"Grandharvas").update_all(fem_level: 0)
Artist.where(name:"Bloc Party").update_all(fem_level: 0)
Artist.where(name:"Chad VanGaalen").update_all(fem_level: 0)
Artist.where(name:"The Flaming Lips").update_all(fem_level: 0)
Artist.where(name:"The Dead Weather").update_all(fem_level: 3)
Artist.where(name:"Thom Yorke").update_all(fem_level: 0)
Artist.where(name:"Portugal. The Man").update_all(fem_level: 0)
Artist.where(name:"Matt Good").update_all(fem_level: 0)
Artist.where(name:"Reuben And The Dark").update_all(fem_level: 0)
Artist.where(name:"The Belle Game").update_all(fem_level: 3)
Artist.where(name:"HAIM").update_all(fem_level: 2)
Artist.where(name:"Whitehorse").update_all(fem_level: 3)
Artist.where(name:"Passion Pit").update_all(fem_level: 0)
Artist.where(name:"Frank Turner").update_all(fem_level: 0)
Artist.where(name:"Elton John").update_all(fem_level: 0)
Artist.where(name:"Lowell").update_all(fem_level: 2)
Artist.where(name:"The 1975").update_all(fem_level: 0)
Artist.where(name:"The The").update_all(fem_level: 0)
Artist.where(name:"Foals").update_all(fem_level: 0)
Artist.where(name:"Cults").update_all(fem_level: 2)
Artist.where(name:"Walk the Moon").update_all(fem_level: 0)
Artist.where(name:"TV On the Radio").update_all(fem_level: 0)
Artist.where(name:"Dirty Vegas").update_all(fem_level: 0)
Artist.where(name:"Len").update_all(fem_level: 1)
Artist.where(name:"The Bottle Rockets").update_all(fem_level: 0)
Artist.where(name:"The Afghan Whigs").update_all(fem_level: 0)
Artist.where(name:"The Hold Steady").update_all(fem_level: 0)
Artist.where(name:"White Denim").update_all(fem_level: 0)
Artist.where(name:"Jonathan Wilson").update_all(fem_level: 0)
Artist.where(name:"Nancy Sinatra").update_all(fem_level: 2)
Artist.where(name:"Northcote").update_all(fem_level: 0)
Artist.where(name:"The War On Drugs").update_all(fem_level: 0)
Artist.where(name:"Nick Cave").update_all(fem_level: 0)
Artist.where(name:"Stevie Wonder").update_all(fem_level: 0)
Artist.where(name:"Diamond Rings").update_all(fem_level: 0)
Artist.where(name:"The Balconies").update_all(fem_level: 2)
Artist.where(name:"Freddy Scott").update_all(fem_level: 0)
Artist.where(name:"The Presidents of the United States of America").update_all(fem_level: 0)
Artist.where(name:"ADELE").update_all(fem_level: 2)
Artist.where(name:"The Head and the Heart").update_all(fem_level: 1)
Artist.where(name:"Musical Youth").update_all(fem_level: 0)
Artist.where(name:"Wolf Parade").update_all(fem_level: 0)
Artist.where(name:"Caribou").update_all(fem_level: 0)
Artist.where(name:"Eight and a Half").update_all(fem_level: 0)
Artist.where(name:"AFI").update_all(fem_level: 0)
Artist.where(name:"Bravestation").update_all(fem_level: 0)
Artist.where(name:"New Politics").update_all(fem_level: 0)
Artist.where(name:"Shad Featuring Lights").update_all(fem_level: 1)
Artist.where(name:"Gord Downie").update_all(fem_level: 0)
Artist.where(name:"Portishead").update_all(fem_level: 2)
Artist.where(name:"Nena").update_all(fem_level: 2)
Artist.where(name:"The Church").update_all(fem_level: 0)
Artist.where(name:"Fun.").update_all(fem_level: 0)
Artist.where(name:"Palma Violets").update_all(fem_level: 0)
Artist.where(name:"Beastie Boys").update_all(fem_level: 0)
Artist.where(name:"Ben Folds").update_all(fem_level: 0)
Artist.where(name:"Divine Fits").update_all(fem_level: 0)
Artist.where(name:"Cold War Kids").update_all(fem_level: 0)
Artist.where(name:"Jake Bugg").update_all(fem_level: 0)
Artist.where(name:"Fleetwood Mac").update_all(fem_level: 2)
Artist.where(name:"Jay Farrar And Benjamin Gibbard").update_all(fem_level: 0)
Artist.where(name:"Gordon Lightfoot").update_all(fem_level: 0)
Artist.where(name:"Temples").update_all(fem_level: 0)
Artist.where(name:"Big Star").update_all(fem_level: 0)
Artist.where(name:"Simon & Garfunkel").update_all(fem_level: 0)
Artist.where(name:"The Cribs").update_all(fem_level: 0)
Artist.where(name:"Bob Marley").update_all(fem_level: 0)
Artist.where(name:"The Roots").update_all(fem_level: 0)
Artist.where(name:"Young MC").update_all(fem_level: 0)
Artist.where(name:"Audioslave").update_all(fem_level: 0)
Artist.where(name:"Cookie Duster").update_all(fem_level: 1)
Artist.where(name:"Boy & Bear").update_all(fem_level: 0)
Artist.where(name:"Plants and Animals").update_all(fem_level: 0)
Artist.where(name:"Santigold").update_all(fem_level: 2)
Artist.where(name:"Band of Skulls").update_all(fem_level: 0)
Artist.where(name:"Great Bloomers").update_all(fem_level: 0)
Artist.where(name:"Lo Fidelity Allstars").update_all(fem_level: 0)
Artist.where(name:"The Preatures").update_all(fem_level: 3)
Artist.where(name:"Björk").update_all(fem_level: 2)
Artist.where(name:"Lana Del Rey").update_all(fem_level: 2)
